run_name: ddpm
test_imple: False
seed: 42
data_dir: ./data/imagenet100_128x128
image_size: 128
batch_size: 30
num_workers: 4
num_classes: #NUM_CLASSES
num_epochs: 10
learning_rate: 0.001
weight_decay: 0.0001
num_train_timesteps: 1000
num_inference_steps: 50

beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

clip_sample: True
clip_sample_range: 1.0

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

cfg_guidance_scale: